//@prepros-append vendors/maskedinput.js
//@prepros-append vendors/jquery.fancybox.min.js
//@prepros-append vendors/device.min.js
//@prepros-append vendors/flickity.pkgd.min.js
//@prepros-append vendors/vivus.min.js
//@prepros-append vendors/countdown.min.js
//@prepros-append vendors/waypoints.js
//@prepros-append vendors/fixer.js
//@prepros-append vendors/jquery.fitvids.js